# This file is machine-generated - editing it directly is not advised

julia_version = "1.12.5"
manifest_format = "2.0"
project_hash = "9aa632fed71af14c884bc31f2246ccd0b1ed00d9"

[[deps.SimDES]]
path = "."
uuid = "4b36ed4b-0aee-48cb-8514-e2c6d0980b55"
version = "1.0.0-DEV"
